
const BREAKPOINTS = {
  XXS: 320,
  XS: 414,
  SM: 768,
  MD: 1024,
  LG: 1440,
  MOBILE: 768,
  SMALL_MOBILE: 425
};

const DIMELO_TOKEN = "DIMELO_TOKEN";
const DIMELO_CURRENT_USER = "DIMELO_CURRENT_USER";
const DATE_FORMAT = "MM-DD-YYYY";
const SLIDER_MAX_VALUE = 10000;

export {
  BREAKPOINTS,
  DIMELO_TOKEN,
  DIMELO_CURRENT_USER,
  DATE_FORMAT,
  SLIDER_MAX_VALUE
};
